### ISSUE TITLE
Clef requirements for submissions and grading

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#588]
It is really important for the clef organisers to have a access to the submission files, on one hand to possibly provide additional kind of score(s), on the other hand to also be able to conduct more in depth analysis by maybe evaluating submissions separately based on the approach that was used to solve the problem. I suggest placing a button on the submission tab where organisers can download all submission files (possibly a zip containing all of them) and another button for the download of metadata (eg. :
[{"participant":"ivan.eggel@hevs.ch", submission_file:"submission1_ivan.csv", "meta":{"type":"automatic", "additonal_resources_used":"wikipedia images", "primary_run":true, ...}},

{"participant":"participant2@...., ... , ... ,"meta":{... , .., ...}}, 

...]
. Upon submission it would be good to have an upload field where participants can select the submission file from their local drive and some fields where participants can provide additional information for the submission (type, additional resources, primary_run, etc.).

**Comment by ieggel** [comment]
This issue is broken down into following sub-issues: 
- [x] #565 File submission via web page
- [x] #612 Possibility to provide metadata via web page submission
- [x] #614 Download of all submission metadata and submission files
- [x] #615 Possibility to enable/disable leaderboard view
- [x] #617 Secure access to leaderboard

**Comment by scarroll32** [comment]
Done
