### ISSUE TITLE
Design updates needed

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#827]
- [ ] Leaderboard padding
- [ ] Leaderboard message
https://github.com/crowdAI/crowdai/blob/master/doc/leaderboard_submissions_visibility.md
- [ ] My submissions switch and detail (priority)
- [ ] Doorkeeper view (https://github.com/crowdAI/crowdai/issues/603)
https://gitlab.crowdai.org/users/sign_in
https://gitlab.com/themes-templates
<img width="857" alt="screen shot 2018-06-19 at 10 23 20" src="https://user-images.githubusercontent.com/11340230/41585589-d41454b0-73aa-11e8-8328-72a5b92c64ff.png">

- [ ] Submissions page (https://github.com/crowdAI/crowdai/issues/406)
- [ ] Cookie consent  (priority)
https://github.com/infinum/cookies_eu
https://github.com/crowdAI/crowdai/issues/851
- [ ] Mentions (https://github.com/crowdAI/crowdai/issues/707) (priority)
 
<img width="339" alt="screen shot 2018-06-19 at 10 31 20" src="https://user-images.githubusercontent.com/11340230/41585992-ed0c61f0-73ab-11e8-9669-7ec8b7bce7a9.png">

- [ ] Teams (https://github.com/crowdAI/crowdai/issues/325)
- [ ] Re-think Multiple organizers (https://github.com/crowdAI/crowdai/issues/706) (priority)
- [ ] Admin styling
ActiveAdmin 
- [ ] GDPR download interface
- [ ] Accept cookies styling (https://github.com/crowdAI/crowdai/issues/851)
- [ ] Latest news banner (https://github.com/crowdAI/crowdai/issues/853)
- [ ] Badges

**Comment by scarroll32** [comment]
Have been covered elsewhere.
